### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by wiilover22** [JEFF-Media-GbR/Spigot-InvUnloadPlus#45] opened 2021-05-16 22:35 UTC
Java version: OpenJDK 64-Bit 16.0.1
OS: Ubuntu 18.04
Minecraft server: git-Paper-685 (MC: 1.16.5)

Error:
`[18:12:43 ERROR]: Error occurred while enabling InvUnload v4.12.1 (Is it up to date?)
java.lang.ClassCastException: class de.jeff_media.ChestSort.ChestSortPlugin cannot be cast to class de.jeff_media.ChestSortAPI.ChestSort (de.jeff_media.ChestSort.ChestSortPlugin is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @28ce7a98; de.jeff_media.ChestSortAPI.ChestSort is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @42500b21)
	at de.jeff_media.InvUnload.Main.onEnable(Main.java:98) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-685]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.16.5.jar:git-Paper-685]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-685]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:504) ~[patched_1.16.5.jar:git-Paper-685]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:418) ~[patched_1.16.5.jar:git-Paper-685]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:592) ~[patched_1.16.5.jar:git-Paper-685]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281) ~[patched_1.16.5.jar:git-Paper-685]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1066) ~[patched_1.16.5.jar:git-Paper-685]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-685]
	at java.lang.Thread.run(Unknown Source) [?:?]`

Plugin was working a little while ago, decided to update to Java 16 and newest Spigot version. Could have been either. Willing to do some testing if necessary.

**Comment by mfnalex** [comment] 2021-05-17 12:02
Hi, I cannot reproduce this, I tried with the following Java versions:

- JRE 1.8.0_271
- JDK 1.8.0_271
- JDK 11.0.9
- JDK 15
- JDK 16.0.1

Can you send your full server.log in a ticket on my Discord please?

https://discord.jeff-media.de

**Comment by wiilover22** [comment] 2021-05-17 13:25
I am using the latest versions of both plugins from SpigotMC. Double checked. I did **not** compile them myself. Posting a ticket on your Discord as requested.

**Comment by mfnalex** [comment] 2021-05-19 12:12
Try downgrading Paper to 671 pls

**Comment by mfnalex** [comment] 2021-05-19 13:31
Fixed in ChestSort 10.0.0 and InvUnload 2.13.0. Works with latest Spigot and Paper.

**Closed by mfnalex** 2021-05-19 13:31 UTC
